# Generated by Django 4.2.2 on 2023-07-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_vehiculo_category_vehiculo_price_vehiculo_serial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='category',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('TRANSPORTE', 'Trasporte'), ('CARGA', 'Carga')], max_length=20, null=True, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='title',
            field=models.CharField(choices=[('FIAT', 'Fiat'), ('CHEVROLET', 'Chevrolet'), ('FORD', 'Ford'), ('TOYOTA', 'Toyota')], max_length=20, verbose_name='marca'),
        ),
    ]
