# Generated by Django 4.0.5 on 2023-07-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_boards_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'permissions': (('visualizar_catalogo', 'puede ver el catalogo'),)},
        ),
    ]
