# Generated by Django 4.0.5 on 2023-07-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_boards_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'permissions': (('es_miembro_1', 'es miembro con prioridad 1'),)},
        ),
    ]
