# Generated by Django 4.0.5 on 2023-07-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_visualizar_permiso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visualizar_Permiso',
            new_name='Visualizar_Catalogo',
        ),
    ]
