# Generated by Django 4.0.5 on 2023-07-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_rename_visualizar_permiso_visualizar_catalogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boards',
        ),
        migrations.AlterModelOptions(
            name='visualizar_catalogo',
            options={'permissions': (('visualizar_catalogo', 'Visualizar Catalogo'),)},
        ),
    ]
