# Generated by Django 4.0.5 on 2023-07-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_delete_boards_alter_visualizar_catalogo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visualizar_catalogo',
            options={},
        ),
    ]
