# Generated by Django 4.0.5 on 2023-07-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_alter_visualizar_catalogo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visualizar_Catalogo',
        ),
    ]
