# Generated by Django 4.0.5 on 2023-07-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_visualizar_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='title',
            field=models.CharField(choices=[('FIAT', 'Fiat'), ('CHEVROLET', 'Chevrolet'), ('FORD', 'Ford'), ('TOYOTA', 'Toyota')], default='Ford', max_length=20, verbose_name='marca'),
        ),
    ]
