# Generated by Django 4.0.5 on 2023-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_alter_vehiculo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
