# Generated by Django 4.0.5 on 2023-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_alter_vehiculo_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_vehiculomodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='category',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('TRANSPORTE', 'Trasporte'), ('CARGA', 'Carga')], default='Particular', max_length=20, null=True, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='title',
            field=models.CharField(choices=[('FIAT', 'Fiat'), ('CHEVROLET', 'Chevrolet'), ('FORD', 'Ford'), ('TOYOTA', 'Toyota')], default='Ford', max_length=20, null=True, verbose_name='marca'),
        ),
    ]
